### ISSUE TITLE
Training Scripts for Tanks and Temples

### ISSUE THREAD

**Issue by kevinyu-0910** [mbortolon97/6dgs#2]
First of all, I would like to express my gratitude for your work and efforts in developing this project. I am experiencing some issues while running the training scripts in your project. When I execute the commands:
```sh
sh tools/launch_all_tanks_and_temple_training.sh
```
I encounter issues that seem to be related to the path settings in tanksandtemples.py:
```sh
path_base = "/home/mbortolon/data/datasets/onepose/train_data/0000-catterpillar"
os.makedirs(path_base, exist_ok=True)
```
Additionally, I am facing issues while training the 'Ignatius' scene. Could you provide some guidance on how to resolve these problems?
![image](https://github.com/user-attachments/assets/2ecd6169-fbb4-444c-997e-6779a4f7afd7)

Thank you for your help!

Best regards

**Comment by kevinyu-0910** [comment]
I downloaded it again from the link in the README.md, but the same issue still occurs.

**Comment by mbortolon97** [comment]
Ah, okay. I'm sorry I forgot about this; Ignatius has a misformatted intrinsic.txt. I have attached the correct file; if you replace it, it should not cause any more issues.
[intrinsics.txt](https://github.com/user-attachments/files/16413568/intrinsics.txt)

For the rest of the scenes, tell me if the problem is fixed. Otherwise, if you can give more details, I will be happy to help.

**Comment by kevinyu-0910** [comment]
Replaced with the provided file, it can run normally, and other scenarios can also run normally. Thank you for your help.
